/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Notification {
  'id' : bigint,
  'studentEmail' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'testId' : bigint,
}
export interface Student {
  'displayName' : string,
  'joinedAt' : bigint,
  'email' : string,
}
export interface StudyMaterial {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'fileName' : string,
  'blobId' : string,
  'uploadedAt' : bigint,
}
export interface Test {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'durationMinutes' : bigint,
  'questionBlobId' : string,
}
export interface TestAttempt {
  'marks' : [] | [bigint],
  'studentEmail' : string,
  'startedAt' : bigint,
  'answerBlobId' : [] | [string],
  'testId' : bigint,
  'tabSwitchCount' : bigint,
  'isComplete' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudyMaterial' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignMarks' : ActorMethod<
    [bigint, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createTest' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'deleteStudyMaterial' : ActorMethod<[bigint], undefined>,
  'deleteTest' : ActorMethod<[bigint], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCode' : ActorMethod<[], string>,
  'getMyAttempts' : ActorMethod<[string], Array<TestAttempt>>,
  'getMyProfile' : ActorMethod<[string], [] | [Student]>,
  'getNotifications' : ActorMethod<[string], Array<Notification>>,
  'getQuestionPaper' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getTestAttempts' : ActorMethod<[bigint], Array<TestAttempt>>,
  'getTests' : ActorMethod<[], Array<Test>>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinClass' : ActorMethod<
    [string, string, string],
    { 'ok' : Student } |
      { 'err' : string }
  >,
  'markAllNotificationsRead' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<[string, bigint], undefined>,
  'reportTabSwitch' : ActorMethod<[string, bigint], undefined>,
  'startTest' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitAnswerPaper' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];