/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TestAttempt = IDL.Record({
  'marks' : IDL.Opt(IDL.Nat),
  'studentEmail' : IDL.Text,
  'startedAt' : IDL.Int,
  'answerBlobId' : IDL.Opt(IDL.Text),
  'testId' : IDL.Nat,
  'tabSwitchCount' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const Student = IDL.Record({
  'displayName' : IDL.Text,
  'joinedAt' : IDL.Int,
  'email' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'studentEmail' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'testId' : IDL.Nat,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'blobId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'durationMinutes' : IDL.Nat,
  'questionBlobId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudyMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignMarks' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteStudyMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteTest' : IDL.Func([IDL.Nat], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCode' : IDL.Func([], [IDL.Text], ['query']),
  'getMyAttempts' : IDL.Func([IDL.Text], [IDL.Vec(TestAttempt)], ['query']),
  'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getNotifications' : IDL.Func([IDL.Text], [IDL.Vec(Notification)], ['query']),
  'getQuestionPaper' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getTestAttempts' : IDL.Func([IDL.Nat], [IDL.Vec(TestAttempt)], ['query']),
  'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinClass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Student, 'err' : IDL.Text })],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([IDL.Text], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'reportTabSwitch' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'startTest' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitAnswerPaper' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TestAttempt = IDL.Record({
    'marks' : IDL.Opt(IDL.Nat),
    'studentEmail' : IDL.Text,
    'startedAt' : IDL.Int,
    'answerBlobId' : IDL.Opt(IDL.Text),
    'testId' : IDL.Nat,
    'tabSwitchCount' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const Student = IDL.Record({
    'displayName' : IDL.Text,
    'joinedAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'studentEmail' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'testId' : IDL.Nat,
  });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'blobId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'durationMinutes' : IDL.Nat,
    'questionBlobId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudyMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignMarks' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteStudyMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteTest' : IDL.Func([IDL.Nat], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCode' : IDL.Func([], [IDL.Text], ['query']),
    'getMyAttempts' : IDL.Func([IDL.Text], [IDL.Vec(TestAttempt)], ['query']),
    'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getQuestionPaper' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getTestAttempts' : IDL.Func([IDL.Nat], [IDL.Vec(TestAttempt)], ['query']),
    'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinClass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Student, 'err' : IDL.Text })],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([IDL.Text], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'reportTabSwitch' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'startTest' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitAnswerPaper' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };